
---
- name: junos_facts module
  hosts: vsrx1
  connection: local
  gather_facts: no
  tasks:

  ## This playbook will query facts and configuration in text format on vsrx1
  ## and Store the configuration in the local directory

  - name: Collect facts and configurion in text on device
    junos_facts:
      config: yes
      config_format: text
      provider: "{{ credential }}"
    register: result

  # - debug: var=result

  - name: Save configuration to file in local directory
    copy: content="{{ result.ansible_facts.config }}" dest=./{{ inventory_hostname }}.save.conf
